version: '3.1'

services:
  angular-app:
    restart: always
    container_name: angular
    image: node:14.16.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 9090:8000
    command: [sh, -c, "cd application/app && npm install && npm install -g bower && bower install --force-latest --allow-root && npm run dev"]
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - bower
    expose:
      - 9090

  # bower:
  #   restart: always
  #   container_name: bower
  #   image: node:14.16.1
  #   working_dir: /frontend
  #   volumes:
  #     - .:/frontend
  #   command: npm install -g bower && bower install --allow-root 

  nginx:
    container_name: nginx
    image: nginx:1.17-alpine
    volumes:
      - ./application/nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./application/api-lumen/app/public:/var/www/html/app/public
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "82:82"
  php:
    container_name: php
    build: application/api-lumen
    volumes:
      - ./application/api-lumen:/var/www/html
    working_dir: /var/www/html/app
    command: sh -c "ls && composer install --no-dev --optimize-autoloader && php -S 0.0.0.0:9000 -t public"
    links:
      - db
      - cache
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
    ports:
      - "9000:9000"
    expose: 
        - 9000

  cors:
    build: 
        context: ./application/nginx
        dockerfile: Dockerfile
    container_name: cors
    ports:
      - "4545:80"      

  db:
    container_name: db
    image: mysql:8.0.36
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${DB_EXTERNAL_PORT}:33006
    volumes:
      - ./db_init_scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    expose: 
        - 33006

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:8080

  cache:
    container_name: cache
    image: memcached:1.6-alpine

volumes:
  mysql_data:
    name: lextracking_db
