name: Deploy

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key for Development
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ${{ secrets.DEVELOP_PATH }}
            git pull
            docker restart php
            docker restart angular

      - name: Execute remote SSH commands using SSH key for Production
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE }}
          port: ${{ secrets.SSH_PORT }}
          script: | 
            cd ${{ secrets.PRODUCTION_PATH }}
            git pull
            docker restart php-prod
            docker restart angular-prod
